micronaut:
  application:
    name: campeonato
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    context-path: /api/campeonato/v1

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/campeonato
    dialect: postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '12345'

jpa:
  default:
    entity-scan:
      packages: 'com.campeonato.infrastructure.persistence.entity'
    properties:
      hibernate:
        show_sql: false